name: travel
description: A new Travel Application
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  convert: ^3.1.1
  flutter_native_splash: ^2.2.19
  flutter_svg: ^2.0.9
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:     
    - Assets/Images/
   
  
flutter_icons:
  image_path: "Assets/Images/react.png"
  adaptive_icon_foreground: "Assets/Images/react.png"
  android: true
  ios: true
  adaptive_icon_background: "#1F1B16"


flutter_native_splash:
  color: "#FFFBFF"
  color_dark: "#1F1B16"
  image: "Assets/Images/react.png"
  image_dark: "Assets/Images/react.png"
  android: true
  ios: true
